### ISSUE TITLE
Create documentation for both master and executor.

### ISSUE THREAD

**Issue by shivam05011996** [deep-compute/jobzilla#5]

**Comment by prashanthellina** [comment]
@shivam05011996 Please provide basic documentation for installation and usage.

**Comment by shivam05011996** [comment]
@prashanthellina We will prepare and give PR by Thursday or before.

**Comment by shivam05011996** [comment]
We will be not working on this in the near future. Once a product is out maybe we will resume working on this.

**Comment by shivam05011996** [comment]
We will be not working on this is near future moving to ready.

**Comment by shivam05011996** [comment]
Issue no longer valid, as this project will be depreciated. A new open source tool will be used as replacement if required. Closing.
